pkg load miscellaneous;

c = physical_constant('speed of light in vacuum')
h = physical_constant('Planck constant')
q = physical_constant('elementary charge')
G = physical_constant('Newtonian constant of gravitation')
kB = physical_constant('Boltzmann constant')
NA = physical_constant('Avogadro constant')
me = physical_constant('electron mass')
mp = physical_constant('proton mass')
mn = physical_constant('neutron mass')
u = physical_constant('unified atomic mass unit')
alpha = physical_constant('fine-structure constant')
R = physical_constant('molar gas constant')
p0 = physical_constant('standard atmosphere')
aB = physical_constant('Bohr radius')
ge = physical_constant('electron g factor')
muB = physical_constant('Bohr magneton')
RK = physical_constant('von Klitzing constant')
F = physical_constant('Faraday constant')
sigma = physical_constant('Stefan-Boltzmann constant')
eV = physical_constant('electron volt')
Ha = physical_constant('Hartree energy')
